-- V1: Create core tables

CREATE TABLE SETOR (
  ID BIGINT AUTO_INCREMENT,
  NOME VARCHAR(100) NOT NULL,
  GESTOR VARCHAR(100),
  META_CONSUMO_MENSAL DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE EQUIPAMENTO (
  ID BIGINT AUTO_INCREMENT,
  SETOR_ID BIGINT NOT NULL,
  NOME VARCHAR(100) NOT NULL,
  TIPO VARCHAR(60),
  POTENCIA_NOMINAL DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_EQUIP_SETOR FOREIGN KEY (SETOR_ID) REFERENCES SETOR(ID)
);

CREATE TABLE LEITURA_SENSOR (
  ID BIGINT AUTO_INCREMENT,
  EQUIPAMENTO_ID BIGINT NOT NULL,
  CONSUMO_KWH DECIMAL(15,6) NOT NULL,
  TS_LEITURA TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_LEITURA_EQUIP FOREIGN KEY (EQUIPAMENTO_ID) REFERENCES EQUIPAMENTO(ID)
);

CREATE TABLE ALERTA_ENERGIA (
  ID BIGINT AUTO_INCREMENT,
  EQUIPAMENTO_ID BIGINT,
  SETOR_ID BIGINT,
  TIPO_ALERTA VARCHAR(30) NOT NULL,
  MENSAGEM VARCHAR(400),
  SEVERIDADE VARCHAR(20) NOT NULL,
  CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_ALERTA_EQUIP FOREIGN KEY (EQUIPAMENTO_ID) REFERENCES EQUIPAMENTO(ID),
  CONSTRAINT FK_ALERTA_SETOR FOREIGN KEY (SETOR_ID) REFERENCES SETOR(ID)
);

CREATE TABLE CONSUMO_DIARIO (
  ID BIGINT AUTO_INCREMENT,
  EQUIPAMENTO_ID BIGINT NOT NULL,
  DIA DATE NOT NULL,
  TOTAL_KWH DECIMAL(15,6) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_CONS_DIAR_EQUIP FOREIGN KEY (EQUIPAMENTO_ID) REFERENCES EQUIPAMENTO(ID),
  CONSTRAINT UQ_CONSUMO_DIARIO UNIQUE (EQUIPAMENTO_ID, DIA)
);


