-- V2: Create required indexes

CREATE INDEX IDX_LEITURA_SENSOR_TS ON LEITURA_SENSOR (TS_LEITURA);
CREATE INDEX IDX_ALERTA_TIPO ON ALERTA_ENERGIA (TIPO_ALERTA);
CREATE INDEX IDX_ALERTA_SETOR ON ALERTA_ENERGIA (SETOR_ID);
CREATE INDEX IDX_EQUIP_SETOR ON EQUIPAMENTO (SETOR_ID);
CREATE INDEX IDX_LEITURA_EQUIP ON LEITURA_SENSOR (EQUIPAMENTO_ID);
CREATE INDEX IDX_CONS_DIAR_EQUIP ON CONSUMO_DIARIO (EQUIPAMENTO_ID);


