-- V3: Seed minimal data for tests

INSERT INTO SETOR (NOME, GESTOR, META_CONSUMO_MENSAL) VALUES ('Operações', 'Maria Silva', 5000);
INSERT INTO SETOR (NOME, GESTOR, META_CONSUMO_MENSAL) VALUES ('TI', 'João Souza', 3000);

INSERT INTO EQUIPAMENTO (SETOR_ID, NOME, TIPO, POTENCIA_NOMINAL) VALUES (1, 'Chiller 01', 'Refrigeração', 50.0);
INSERT INTO EQUIPAMENTO (SETOR_ID, NOME, TIPO, POTENCIA_NOMINAL) VALUES (2, 'Servidor 01', 'TI', 5.0);


