name: CI/CD Pipeline

on:
  push:
    branches:
      - pipeline
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: mvn clean install

      - name: Rodar testes
        run: mvn test

      - name: Build Docker
        run: docker build -t smart-energy .